/**
 * Bridge-profile provisioning for DeepShian.
 *
 * The plugin drives the local dsh CLI with `dsh --profile deepshian`; that
 * profile lives in the dsh home (default ~/.dsh/profiles/<name>) and must
 * contain this repo's bridge files. On a fresh machine nothing is installed
 * yet, so the plugin detects the missing or mismatched profile and provisions
 * it from the files baked into main.js at build time (see the `?raw` imports,
 * kept in sync with the repo's dsh-profile/deepshian/ folder).
 *
 * cordis.patch.yml is GENERATED with the machine's real home path — the repo
 * template cannot know it. Hard-coding a developer's C:/Users/... path here is
 * exactly what broke manual copies on other machines.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

import bridgeSource from "../../dsh-profile/deepshian/deepshian-bridge.mjs?raw";
import cordisYml from "../../dsh-profile/deepshian/cordis.yml?raw";
import profilePackageJson from "../../dsh-profile/deepshian/package.json?raw";

/** Bridge profile name (matches --profile and $DSH_HOME/profiles/<name>). */
export const DEFAULT_PROFILE = "deepshian";
export const BRIDGE_FILE = "deepshian-bridge.mjs";

/** dsh home: honor $DSH_HOME, fall back to ~/.dsh. */
export function dshHome(): string {
	return process.env.DSH_HOME?.trim() || join(homedir(), ".dsh");
}

/** Directory dsh reads the profile from: <dshHome>/profiles/<name>. */
export function profileDir(name: string): string {
	return join(dshHome(), "profiles", name);
}

function fileUri(p: string): string {
	return "file:///" + p.replace(/\\/g, "/");
}

/** Rebuild cordis.patch.yml pointing at THIS machine's bridge file. */
function patchContent(name: string): string {
	return [
		"# DeepShian bridge profile — generated by the plugin on this machine.",
		"- insert:",
		"    - id: deepshian-bridge",
		`      name: ${fileUri(join(profileDir(name), BRIDGE_FILE))}`,
		"",
	].join("\n");
}

/** All profile files present (cordis.yml + the bridge). */
export function detectProfile(name: string): boolean {
	const dir = profileDir(name);
	return (
		existsSync(join(dir, "cordis.yml")) && existsSync(join(dir, BRIDGE_FILE))
	);
}

/** True when the installed patch points at this machine's bridge file. */
export function patchPathHealthy(name: string): boolean {
	const file = join(profileDir(name), "cordis.patch.yml");
	try {
		return readFileSync(file, "utf8").includes(
			fileUri(join(profileDir(name), BRIDGE_FILE)),
		);
	} catch {
		return false;
	}
}

/** Write (or idempotently overwrite) the four profile files. Throws on failure. */
export function installProfile(name: string): void {
	const dir = profileDir(name);
	mkdirSync(dir, { recursive: true });
	writeFileSync(join(dir, "package.json"), profilePackageJson);
	writeFileSync(join(dir, "cordis.yml"), cordisYml);
	writeFileSync(join(dir, BRIDGE_FILE), bridgeSource);
	writeFileSync(join(dir, "cordis.patch.yml"), patchContent(name));
}